import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Analytics } from "@vercel/analytics/next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}>
        <div className="flex flex-col  min-h-dvh">
          <header className="flex gap-6 flex-wrap justify-end pt-6 pr-6 fixed sticky top-0 bg-[#6c844c] text-[#f9e6bf] pb-6 z-1000">
            <Link href="/">Main Page</Link>
            <a href="/skinsheet">Skin Sheet</a>
          </header>
          <div className="flex-grow dark my--10 bg-[url(/golf-course-1.png)] bg-scroll bg-cover">{children}</div>
          <Analytics />
          <footer className="row-start-3 fixed flex gap-6 flex-wrap items-center justify-center sticky bottom-0 py-8 bg-[#6c844c] text-[#f9e6bf]">
            <Link href="/">&copy; 2025 GlenHurst - Change Later</Link>
          </footer>
        </div>
      </body>
    </html>
  );
}
