import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Analytics } from "@vercel/analytics/next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}>
        <div className="flex flex-col">
          <header className="flex gap-6 flex-wrap justify-end pt-6 pr-6 sticky top-0 bg-black pb-6">
            <Link href="/">Main Page</Link>
            <a href="/newsletter">News Letter</a>
            <a href="/skinsheet">Skin Sheet</a>
          </header>
          <div className="dark">{children}</div>
          <Analytics />
        </div>
      </body>
    </html>
  );
}
